[moode-apt-mark] Refactor spaces to tabs

diff --git a/packages/moode-player/moode-apt-mark b/packages/moode-player/moode-apt-mark
--- a/packages/moode-player/moode-apt-mark
+++ b/packages/moode-player/moode-apt-mark
@@ -24,11 +24,11 @@ do
   then
 	result=$(dpkg-query --showformat='${Version}\n' --show $package)
 	if [[ $result != "" ]]; then
-	    pkgstr+="$package "
-	    if [ $? -gt 1 ]; then
-	      echo "ERROR: processing $package failed, loop aborted"
-	      exit 1
-	    fi
+		pkgstr+="$package "
+		if [ $? -gt 1 ]; then
+		  echo "ERROR: processing $package failed, loop aborted"
+		  exit 1
+		fi
 	else
 		echo "INFO: $package skipped, not installed"
 	fi
@@ -37,6 +37,6 @@ done < "$package_list"
 apt-mark "$cmd" $pkgstr
 if [ $? -gt 1 ]
 then
-    echo "ERROR: apt-mark $cmd failed on a package in the list"
-    exit 1
+	echo "ERROR: apt-mark $cmd failed on a package in the list"
+	exit 1
 fi
