[moode-apt-mark] Exclude packages that are not installed
This is to avoid error exit due to librespot or shairport-sync not being installed which is the default on 10.2.0 or higher releases.

diff --git a/packages/moode-player/moode-apt-mark b/packages/moode-player/moode-apt-mark
--- a/packages/moode-player/moode-apt-mark
+++ b/packages/moode-player/moode-apt-mark
@@ -8,10 +8,9 @@
 #
 #########################################################################
 
-echo "moOde-apt-hold"
 if [[ -z "$1" ]] || [[ "$1" != "hold" ]] && [[  "$1" != "unhold" ]]
 then
-   echo "Argument should be hold or unhold."
+   echo "Arguments are [hold | unhold]"
    exit
 fi
 
@@ -20,21 +19,24 @@ pkgstr=""
 package_list="/etc/moode-apt-mark.conf"
 while IFS= read -r line
 do
-
   package=`echo "$line" | sed -e 's/[[:space:]]*#.*// ; /^[[:space:]]*$/d'`
   if [[ -n "$package" ]]
   then
-    pkgstr+="$package "
-    if [ $? -gt 1 ]
-    then
-      echo "Oops something went wrong, aborting ..."
-      exit 1
-    fi
+	result=$(dpkg-query --showformat='${Version}\n' --show $package)
+	if [[ $result != "" ]]; then
+	    pkgstr+="$package "
+	    if [ $? -gt 1 ]; then
+	      echo "ERROR: processing $package failed, loop aborted"
+	      exit 1
+	    fi
+	else
+		echo "INFO: $package skipped, not installed"
+	fi
   fi
 done < "$package_list"
-apt-mark "$cmd" "$package" $pkgstr
+apt-mark "$cmd" $pkgstr
 if [ $? -gt 1 ]
 then
-    echo "Oops something went wrong"
+    echo "ERROR: apt-mark $cmd failed on a package in the list"
     exit 1
 fi
